sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-aarch64-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1/qemu-aarch64-static.tar.gz &&
  tar xzf qemu-aarch64-static.tar.gz &&
  popd
# build image
- docker build -t spanghf37/emoncms .
# test image
- docker run spanghf37/emoncms uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag spanghf37/emoncms spanghf37/emoncms:$TAG
    docker tag spanghf37/emoncms spanghf37/emoncms:latest
    docker push spanghf37/emoncms:$TAG
    docker push spanghf37/emoncms:latest
  fi
