version: '2.1'

services:

  web:
    env_file: .env
    image: spanghf37/emoncms:amd64
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - /mnt/data/configs/emoncms/emon-phpfiwa:/var/lib/phpfiwa
      - /mnt/data/configs/emoncms/emon-phpfina:/var/lib/phpfina
      - /mnt/data/configs/emoncms/emon-phptimeseries:/var/lib/phptimeseries
    ports:
      # Expose Emoncms on localhost port 8080
      - 8080:80
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    healthcheck:
      test: "curl -f http://localhost:80/emoncms"
      interval: 1s
      retries: 120
    depends_on:
      db:
        condition: service_healthy
  # MYSQL Database
  db:
    # Official MYSQL docker image
    env_file: .env
    image: amd64/mysql:latest
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    restart: always
    volumes:
      - /mnt/data/configs/emoncms/emon-db-data:/var/lib/mysql
  redis:
    # Official redis image
    image: amd64/redis:latest
    env_file:
      - '.env'
    restart: always
    volumes:
      - /mnt/data/configs/emoncms/emon-redis-data:/data

volumes:
  emon-phpfiwa:
  emon-phpfina:
  emon-phptimeseries:
  emon-db-data:
  emon-redis-data:
