# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '3'

services:

  # PHP & apache container using offical Docker PHP iamge
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms) if not Buildcontainer see Dockerflile
    image: spanghf37/emoncms:amd64
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - /mnt/data/configs/emoncms/emon-phpfiwa:/var/lib/phpfiwa
      - /mnt/data/configs/emoncms/emon-phpfina:/var/lib/phpfina
      - /mnt/data/configs/emoncms/emon-phptimeseries:/var/lib/phptimeseries
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    command: ["chown", "www-data:root", "/var/lib/phpfiwa", ";", "chown", "www-data:root", "/var/lib/phpfina", ";", "chown", "www-data:root", "/var/lib/phptimeseries"]
  # MYSQL Database
  db:
    # Official MYSQL docker image
    image: amd64/mysql:latest
    environment:
      - "MYSQL_HOST=localhost"
    volumes:
      - /mnt/data/configs/emoncms/emon-db-data:/var/lib/mysql
  redis:
    # Official redis image
    image: amd64/redis:latest
    volumes:
      - /mnt/data/configs/emoncms/emon-redis-data:/data

volumes:
  emon-phpfiwa:
 #   driver: local
  emon-phpfina:
 #   driver: local
  emon-phptimeseries:
 #   driver: local
  emon-db-data:
 #   driver: local
  emon-redis-data:
 #   driver: local
