# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2.1'

services:

  # PHP & apache container using offical Docker PHP iamge
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms) if not Buildcontainer see Dockerflile
    image: spanghf37/emoncms:amd64
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - /mnt/data/configs/emoncms/emon-phpfiwa:/var/lib/phpfiwa
      - /mnt/data/configs/emoncms/emon-phpfina:/var/lib/phpfina
      - /mnt/data/configs/emoncms/emon-phptimeseries:/var/lib/phptimeseries
    ports:
      # Expose Emoncms on localhost port 8080
      - 8080:80
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
  # MYSQL Database
  db:
    # Official MYSQL docker image
    image: amd64/mysql:latest
    restart: always
    env_file:
      - 'emoncms.docker-env'
    healthcheck:
      test: "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    restart: always
    volumes:
      - /mnt/data/configs/emoncms/emon-db-data:/var/lib/mysql
  redis:
    # Official redis image
    image: amd64/redis:latest
    env_file:
      - 'emoncms.docker-env'
    restart: always
    volumes:
      - /mnt/data/configs/emoncms/emon-redis-data:/data

volumes:
  emon-phpfiwa:
  emon-phpfina:
  emon-phptimeseries:
  emon-db-data:
  emon-redis-data:
