# dev enviroment setup

version: '3'
services:

  web:
    ports:
      # Expose Emoncms on localhost port 8080
      - 8080:80
    #volumes:
      ##mount emoncms files from local FS for dev
      #- ./emoncms:/var/www/html
    env_file:
      # Use default enviroment variables file for dev
      - 'default.docker-env'

  db:
    env_file:
      - 'default.docker-env'
  redis:
    env_file:
      - 'default.docker-env'
